<a href="https://colab.research.google.com/github/ridwanpw/TugasDataMining/blob/main/data_mining_1403.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [3]:
dataset = pd.read_csv("dataset.csv")
dataset.shape

(55, 3)

In [ ]:
dataset.head()

  ID FAKTUR                                     BARANG  QTY
0        N1                              Dzikir Tauhid    1
1        N1            Tuhan Maaf Kami Belum Bersyukur    1
2        N1  Project PHP dan MySQL Membuat Web Digital    1
3        N1                                      Hujan    1
4        N1          Pemrograman Android dengan Kotlin    1

In [4]:
dataset.columns = dataset.columns.str.strip()

In [5]:
dataset

   ID FAKTUR                                       BARANG  QTY
0         N1                                Dzikir Tauhid    1
1         N1              Tuhan Maaf Kami Belum Bersyukur    1
2         N1    Project PHP dan MySQL Membuat Web Digital    1
3         N1                                        Hujan    1
4         N1            Pemrograman Android dengan Kotlin    1
5         N1  Membuat Aplikasi dengan Menggunakan Flutter    1
6         N2                                Dzikir Tauhid    1
7         N2              Tuhan Maaf Kami Belum Bersyukur    1
8         N2    Project PHP dan MySQL Membuat Web Digital    1
9         N2                                        Hujan    1
10        N2            Pemrograman Android dengan Kotlin    1
11        N2  Membuat Aplikasi dengan Menggunakan Flutter    1
12        N3                                Dzikir Tauhid    1
13        N3              Tuhan Maaf Kami Belum Bersyukur    1
14        N3    Project PHP dan MySQL Membuat Web Digital    1
15        N3                                        Hujan    1
16        N3            Pemrograman Android dengan Kotlin    1
17        N3  Membuat Aplikasi dengan Menggunakan Flutter    1
18        N4                                Dzikir Tauhid    1
19        N4    Project PHP dan MySQL Membuat Web Digital    1
20        N4                                        Hujan    1
21        N4         Responsive Web Design with Bootstrap    1
22        N4                                  Aroma Karsa    1
23        N4                                         Ayah    1
24        N5                                Dzikir Tauhid    1
25        N5    Project PHP dan MySQL Membuat Web Digital    1
26        N5                                        Hujan    1
27        N5         Responsive Web Design with Bootstrap    1
28        N5                                  Aroma Karsa    1
29        N5                                         Ayah    1
30        N6                                Dzikir Tauhid    1
31        N6    Project PHP dan MySQL Membuat Web Digital    1
32        N6            Pemrograman Android dengan Kotlin    1
33        N6  Membuat Aplikasi dengan Menggunakan Flutter    1
34        N6         Responsive Web Design with Bootstrap    1
35        N6                                  Aroma Karsa    1
36        N7                                Dzikir Tauhid    1
37        N7              Tuhan Maaf Kami Belum Bersyukur    1
38        N7    Project PHP dan MySQL Membuat Web Digital    1
39        N7         Responsive Web Design with Bootstrap    1
40        N7                                  Aroma Karsa    1
41        N7                                         Ayah    1
42        N8    Project PHP dan MySQL Membuat Web Digital    1
43        N8            Pemrograman Android dengan Kotlin    1
44        N8  Membuat Aplikasi dengan Menggunakan Flutter    1
45        N8         Responsive Web Design with Bootstrap    1
46        N8                                         Ayah    1
47        N9                                Dzikir Tauhid    1
48        N9              Tuhan Maaf Kami Belum Bersyukur    1
49        N9    Project PHP dan MySQL Membuat Web Digital    1
50        N9                                        Hujan    1
51        N9                                  Aroma Karsa    1
52       N10            Pemrograman Android dengan Kotlin    1
53       N10  Membuat Aplikasi dengan Menggunakan Flutter    1
54       N10                                  Aroma Karsa    1

In [6]:
# reshape data as per group
data = dataset.groupby(['ID FAKTUR', 'BARANG'])['QTY'].sum().unstack().reset_index().fillna(0).set_index('ID FAKTUR')
data

BARANG,Aroma Karsa,Ayah,Dzikir Tauhid,Hujan,Membuat Aplikasi dengan Menggunakan Flutter,Pemrograman Android dengan Kotlin,Project PHP dan MySQL Membuat Web Digital,Responsive Web Design with Bootstrap,Tuhan Maaf Kami Belum Bersyukur
ID FAKTUR,,,,,,,,,
N1,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
N10,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
N2,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
N3,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0
N4,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
N5,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
N6,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0
N7,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0
N8,0.0,1.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0
N9,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0

In [7]:
# change value of each element to 0 and 1
data = data.apply(lambda x:[1 if y >=1 else 0 for y in x])
data

BARANG,Aroma Karsa,Ayah,Dzikir Tauhid,Hujan,Membuat Aplikasi dengan Menggunakan Flutter,Pemrograman Android dengan Kotlin,Project PHP dan MySQL Membuat Web Digital,Responsive Web Design with Bootstrap,Tuhan Maaf Kami Belum Bersyukur
ID FAKTUR,,,,,,,,,
N1,0,0,1,1,1,1,1,0,1
N10,1,0,0,0,1,1,0,0,0
N2,0,0,1,1,1,1,1,0,1
N3,0,0,1,1,1,1,1,0,1
N4,1,1,1,1,0,0,1,1,0
N5,1,1,1,1,0,0,1,1,0
N6,1,0,1,0,1,1,1,1,0
N7,1,1,1,0,0,0,1,1,1
N8,0,1,0,0,1,1,1,1,0
N9,1,0,1,1,0,0,1,0,1

In [8]:
frequent_itemsets = apriori(data, min_support=0.2, use_colnames=True)
frequent_itemsets

     support                                           itemsets
0        0.6                                      (Aroma Karsa)
1        0.4                                             (Ayah)
2        0.8                                    (Dzikir Tauhid)
3        0.6                                            (Hujan)
4        0.6      (Membuat Aplikasi dengan Menggunakan Flutter)
..       ...                                                ...
127      0.3  (Dzikir Tauhid, Pemrograman Android dengan Kot...
128      0.3  (Dzikir Tauhid, Pemrograman Android dengan Kot...
129      0.3  (Pemrograman Android dengan Kotlin, Membuat Ap...
130      0.2  (Responsive Web Design with Bootstrap, Dzikir ...
131      0.3  (Dzikir Tauhid, Pemrograman Android dengan Kot...

[132 rows x 2 columns]

In [9]:
rule = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
rule

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Ayah),(Aroma Karsa),0.4,0.6,0.3,0.750000,1.250000,0.06,1.600000
1,(Aroma Karsa),(Ayah),0.6,0.4,0.3,0.500000,1.250000,0.06,1.200000
2,(Dzikir Tauhid),(Aroma Karsa),0.8,0.6,0.5,0.625000,1.041667,0.02,1.066667
3,(Aroma Karsa),(Dzikir Tauhid),0.6,0.8,0.5,0.833333,1.041667,0.02,1.200000
4,(Responsive Web Design with Bootstrap),(Aroma Karsa),0.5,0.6,0.4,0.800000,1.333333,0.10,2.000000
...,...,...,...,...,...,...,...,...,...
1095,(Pemrograman Android dengan Kotlin),"(Dzikir Tauhid, Membuat Aplikasi dengan Menggu...",0.6,0.3,0.3,0.500000,1.666667,0.12,1.400000
1096,(Membuat Aplikasi dengan Menggunakan Flutter),"(Dzikir Tauhid, Pemrograman Android dengan Kot...",0.6,0.3,0.3,0.500000,1.666667,0.12,1.400000
1097,(Tuhan Maaf Kami Belum Bersyukur),"(Dzikir Tauhid, Pemrograman Android dengan Kot...",0.5,0.3,0.3,0.600000,2.000000,0.15,1.750000
1098,(Project PHP dan MySQL Membuat Web Digital),"(Dzikir Tauhid, Pemrograman Android dengan Kot...",0.9,0.3,0.3,0.333333,1.111111,0.03,1.050000
1099,(Hujan),"(Dzikir Tauhid, Pemrograman Android dengan Kot...",0.6,0.3,0.3,0.500000,1.666667,0.12,1.400000